version: '3.7'

services:

  frontend:
    restart: always
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 8080:8080
    expose:
      - 8080

  backend:
    restart: always
    container_name: backend
    env_file:
      - ./DB.env
    build: 
      context: ./fastApi
    ports:
      - 8081:8081
    expose:
      - 8081
    depends_on:
      - db
    command: ['uvicorn', 'main:app', '--host=127.0.0.1', '--port=8081']

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=some
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_DB=warmonger
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

volumes:
  pgdata: