# Generated by Django 4.0.4 on 2022-12-11 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('adress', models.CharField(default=' ', max_length=200)),
                ('latitude', models.FloatField(default=1.0)),
                ('longitude', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=90)),
                ('site', models.URLField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=90)),
                ('nickname', models.CharField(default=' ', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=50)),
                ('text', models.TextField(default=' ', max_length=300)),
                ('source', models.CharField(default=' ', max_length=70)),
                ('date', models.DateField(default=datetime.datetime(2022, 12, 11, 16, 31, 14, 448842, tzinfo=utc))),
                ('locations', models.ManyToManyField(to='main.location')),
                ('organisations', models.ManyToManyField(to='main.organisation')),
                ('persons', models.ManyToManyField(to='main.person')),
                ('tags', models.ManyToManyField(to='main.tag')),
            ],
        ),
    ]
